In [43]:
# Merge duplicate files without losing mumerical data when just deleting duplicate files is the only option
# by Jade Nuss

In [44]:
import pandas as pd
import numpy as np

# path of file that may have missing data (MUST BE VERY LARGER in size)
#body1 = r"C:\Users\PRADYUM\Downloads\fhrw-4uyv.csv"

#df = pd.read_csv(body1)
#df.head()

In [45]:
# path of any number of files that may contain the missing data (repeat for each file)
#ff = pd.read_csv(r"C:\Users\PRADYUM\Desktop\PLUTO_for_WEB\BX_18v122.csv")

In [46]:
Merge_factor = 0.089703184

In [47]:
#Output file
Mean_columns = np.array([54321.123, 65432.123, 76543.123]) # replace with mean of numerical values of columns
type(Mean_columns)

numpy.ndarray

In [48]:
#Files to be merged
Merge_mean_columns = np.array([1234.4321,2345.5432,3456.6543]) # replace with mean of numerical values of columns (of merge files)
type(Merge_mean_columns)

numpy.ndarray

In [49]:
# Python SIN Function

import math

Neg_merge = math.sin(Merge_factor)*(-1)

type(Neg_merge)

float

In [50]:
A= Merge_mean_columns * Merge_factor
B= Merge_mean_columns * Merge_factor  
C= Merge_mean_columns * Merge_factor  

In [51]:
print(A,B,C)

[110.7324898  210.40269325 310.0728967 ] [110.7324898  210.40269325 310.0728967 ] [110.7324898  210.40269325 310.0728967 ]


In [52]:
a= Merge_mean_columns * Neg_merge
b= Merge_mean_columns * Neg_merge
c= Merge_mean_columns * Neg_merge

In [53]:
print(a,b,c)

[-110.58404507 -210.12063356 -309.65722205] [-110.58404507 -210.12063356 -309.65722205] [-110.58404507 -210.12063356 -309.65722205]


In [54]:
Distribution_number = ((A+B+C)/5)*-1
type(Distribution_number)

numpy.ndarray

In [55]:
print(Distribution_number)

[ -66.43949388 -126.24161595 -186.04373802]


In [56]:
Mean_columnA_ditributed = np.array([Mean_columns-Distribution_number* Merge_factor+A])
Mean_columnB_ditributed = np.array([Mean_columns-Distribution_number* Merge_factor+B])
Mean_columnC_ditributed = np.array([Mean_columns-Distribution_number* Merge_factor+C])

In [57]:
print(Mean_columnA_ditributed, Mean_columnB_ditributed, Mean_columnC_ditributed)

[[54437.81532395 65653.84996815 76869.88461236]] [[54437.81532395 65653.84996815 76869.88461236]] [[54437.81532395 65653.84996815 76869.88461236]]


In [58]:
x=Distribution_number-Mean_columnA_ditributed*Neg_merge
y=Distribution_number-Mean_columnB_ditributed*Neg_merge
z=Distribution_number-Mean_columnC_ditributed*Neg_merge

print(x,y,z)

[[4810.25953486 5755.22266522 6700.18579558]] [[4810.25953486 5755.22266522 6700.18579558]] [[4810.25953486 5755.22266522 6700.18579558]]


In [59]:
d=(Mean_columnA_ditributed+(x/5)+4000/3) # replace '3' with len(final data column)
d=(Mean_columnB_ditributed+(x/5)+5000/3) # replace '3' with len(final data column)
d=(Mean_columnC_ditributed+(x/5)+6000/3) # replace '3' with len(final data column)
type(d)
print(d)

[[57399.86723092 68804.8945012  80209.92177148]]


In [60]:
# delete mixed files with numberical data added to updated dataframe.  the function is baced on  
# Department of Housing Preservation and Development of New York City's Harvard study.  The maximum amount of complexity of a 
# project is independent of the complexity of housing labor in the greatest population dencity of the US
